pipeline {
    agent any
    tools {nodejs 'NODEJS'}
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Deliver') {
            steps {
                sh 'chmod -R +rwx ./scripts/deliver.sh'
                sh 'chmod -R +rwx ./scripts/kill.sh'
                sh './scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './scripts/kill.sh'
            }
        }
    }
}