pipeline {
    agent any
    tools {nodejs 'NODEJS'}
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                bat 'npm install'
                bat 'npm run build'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deliver') {
            steps {
                // Print the current directory to verify the location
                bat 'cd'
                // bat 'chmod -R +rwx ./scripts/deliver.bat'
                // bat 'chmod -R +rwx ./scripts/kill.bat'
                bat 'jenkins\\scripts\\deliver.bat'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                bat 'jenkins\\scripts\\kill.bat'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}