pipeline {
    agent any
    tools {nodejs 'NODEJS'}
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                bat 'npm install'
            }
        }
        stage('Deliver') {
            steps {
                // Print the current directory to verify the location
                bat 'cd'
                // bat 'chmod -R +rwx ./scripts/deliver.bat'
                // bat 'chmod -R +rwx ./scripts/kill.bat'
                bat 'jenkins\\scripts\\deliver.bat'
                echo 'Now...'
                echo 'Visit http://localhost:3000 to see your Node.js/React application in action.'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                bat 'jenkins\\scripts\\kill.bat'
            }
        }
    }
}